import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    title: "TRICHY POLICE COMMAND CENTER",
    subtitle: "TRICHY DISTRICT SURVEILLANCE & PROACTIVE AI INSPECTOR (GUARDIAN ANGEL AI)",
    cctv: "Camera Monitoring Center",
    dashboard: "Executive Dashboard",
    live_surveillance: "Live Analysis Focus",
    heatmap: "Threat GIS Analysis",
    cameras: "Camera Integration Hub",
    reports: "Incident History",
    settings: "Settings",
    users: "User Operator Accounts",
    area_focus: "Area Focus Monitor",
    system_status: "SYSTEM STATUS",
    secure: "SECURE",
    build: "BUILD",
    online_nodes: "ONLINE NODES",
    offline: "OFFLINE",
    live_core_online: "LIVE CORE ONLINE",
    core_disconnected: "CORE DISCONNECTED",
    live_feed: "LIVE FEED",
    realtime_telemetry: "REAL-TIME TELEMETRY",
    follow_time: "FOLLOW TIME",
    audio_level: "AUDIO LEVEL",
    pedestrians: "PEDESTRIANS",
    pose_status: "POSE STATUS",
    threat_score: "THREAT SCORE",
    proactive_critical_alert: "PROACTIVE CRITICAL ALERT - PATROL DISPATCHED",
    live_cctv_feed_matrix: "LIVE CCTV SURVEILLANCE FEED MATRIX (CONTROL WALL)",
    close_stream_focus: "CLOSE STREAM FOCUS",
    node_status_offline: "NODE_STATUS: OFFLINE",
    unresolved_alerts: "Unresolved Alerts",
    critical_level_incidents: "CRITICAL LEVEL INCIDENT(S)",
    command_simulator: "COMMAND SIMULATOR",
    proactive_multi_sensor_hud: "PROACTIVE MULTI-SENSOR HUD",
    start: "START",
    stop: "STOP",
    progress: "PROGRESS",
    step: "STEP",
    ai_detections: "AI DETECTIONS",
    patrol_dispatched: "🔴 PATROL DISPATCHED",
    elevated_alert: "🟡 ELEVATED ALERT",
    secure_level: "🟢 SECURE LEVEL",
    simulator_idle: "SIMULATOR IDLE. CLICK \"START\" TO COMMENCE THE 14-STEP TACTICAL SAFETY SEQUENCE.",
    alerts_feed: "ALERTS FEED",
    patrol_dispatches: "PATROL DISPATCHES",
    no_active_alerts: "No active safety alerts triggered yet.",
    cctv_evaluated_loop: "CCTV STREAMS ARE CURRENTLY EVALUATED. AI ENGINE LOOP ACTIVE.",
    no_patrol_dispatches: "No patrol dispatches generated.",
    escalated_alerts_routing: "ESCALATED ALARMS WILL APPEAR HERE FOR UNIT ROUTING.",
    escalated: "ESCALATED",
    dispatched: "DISPATCHED",
    resolved: "RESOLVED",
    dispatch_patrol: "DISPATCH PATROL",
    resolve_case: "RESOLVE CASE",
    case_archived: "CASE ARCHIVED",
    resolve: "RESOLVE",
    escalate: "ESCALATE",
    evidence: "EVIDENCE",
    selected_feed: "SELECTED FEED",
    focus_analyzer: "FOCUS ANALYZER / live object bounding locks",
    fps: "FPS",
    latency: "LATENCY",
    streaming_active: "STREAMING ACTIVE",
    take_snapshot: "TAKE SNAPSHOT",
    start_recording: "START RECORDING",
    stop_recording: "STOP RECORDING",
    generate_report: "GENERATE REPORT",
    emergency_alert: "EMERGENCY ALERT",
    live_event_telemetry_logs: "LIVE EVENT TELEMETRY LOGS",
    ai_object_detection_status: "AI OBJECT COGNITIVE DETECTION STATUS",
    person_detection: "PERSON DETECTION",
    vehicle_detection: "VEHICLE DETECTION",
    face_id_lock: "FACE ID LOCK",
    weapon_detection: "WEAPON DETECTION",
    fight_recognition: "FIGHT / STRUGGLE RECOGNITION",
    smoke_fire_engine: "SMOKE & FIRE ENGINE",
    abandoned_object_finder: "ABANDONED OBJECT FINDER",
    detected: "🟢 DETECTED",
    locked: "🟢 LOCKED",
    weapon_alert: "🔴 WEAPON DETECTED",
    violence_alert: "🔴 VIOLENCE DETECTED",
    fire_alert: "🔴 FIRE ALARM",
    abandoned_alert: "🟡 DETECTED",
    safe_clear: "🟢 SAFE - CLEAR",
    clear: "🟢 CLEAR",
    off: "OFF",
    decision_engine: "DECISION ENGINE",
    ai_target_lock: "AI TARGET LOCK CONFIDENCE",
    confidence: "CONF",
    executive_monitoring_dashboard: "EXECUTIVE MONITORING DASHBOARD",
    government_analytics: "GOVERNMENT ANALYTICS & THREAT REPORT SEGMENTS",
    recent_alerts_log: "RECENT ALERTS LOG",
    live_incident_timeline: "LIVE INCIDENT TIMELINE",
    cam: "CAM",
    location: "LOCATION",
    risk: "RISK",
    timestamp: "TIMESTAMP",
    status: "STATUS",
    active_tamil_text: "வருமுன் காப்போம்",
    sec: "s",
    min: "min",
    subway_gate: "Caution: Elevated following behavior and proximity near dark subway gate.",
    pedestrian_anomaly: "Pedestrian anomaly alert.",
    critical_proximity: "CRITICAL ALERT: Proximity under 1.0 meters for 70 seconds. Target showed pacing behavior.",
    normal_flow: "Normal pedestrian flow. Low risk scores across all metrics.",
    select_camera: "SELECT MONITOR NODE",
    focused_feed: "FOCUSED AREA MONITOR HUD",
    threat_console: "THREAT INTEL EVENTS CONSOLE",
    active_caps: "ACTIVE"
  },
  ta: {
    title: "திருச்சி மாநகர காவல் கட்டுப்பாட்டு மையம்",
    subtitle: "திருச்சி மாவட்ட கண்காணிப்பு & செயலூக்க AI ஆய்வாளர் (கார்டியன் ஏஞ்சல் AI)",
    cctv: "கேமரா கண்காணிப்பு மையம்",
    dashboard: "நிர்வாக டாஷ்போர்டு",
    live_surveillance: "நேரடி பகுப்பாய்வு கவனம்",
    heatmap: "அபாய வரைபட பகுப்பாய்வு",
    cameras: "கேமரா இணைப்பு மையம்",
    reports: "சம்பவ வரலாறு",
    settings: "அமைப்புகள்",
    users: "காவல் ஆபரேட்டர் கணக்குகள்",
    area_focus: "வட்டார கண்காணிப்பு மையம்",
    system_status: "கணினி நிலை",
    secure: "பாதுகாப்பானது",
    build: "பதிப்பு",
    online_nodes: "ஆன்லைன் கேமராக்கள்",
    offline: "ஆஃப்லைன்",
    live_core_online: "நேரடி இணைப்பு உள்ளது",
    core_disconnected: "இணைப்பு துண்டிக்கப்பட்டது",
    live_feed: "நேரடி காட்சி",
    realtime_telemetry: "நேரடி அளவீடுகள்",
    follow_time: "பின்தொடரும் நேரம்",
    audio_level: "ஒலி அளவு",
    pedestrians: "நடப்பவர்கள்",
    pose_status: "உடல் நிலை",
    threat_score: "அபாய விகிதம்",
    proactive_critical_alert: "செயலூக்க தீவிர அபாய எச்சரிக்கை - ரோந்து வாகனம் அனுப்பப்பட்டது",
    live_cctv_feed_matrix: "நேரடி கேமரா கண்காணிப்பு கட்டம் (கட்டுப்பாட்டு சுவர்)",
    close_stream_focus: "நேரடி காட்சியை மூடு",
    node_status_offline: "கேமரா நிலை: ஆஃப்லைன்",
    unresolved_alerts: "தீர்க்கப்படாத எச்சரிக்கைகள்",
    critical_level_incidents: "தீவிர அபாய சம்பவங்கள்",
    command_simulator: "கட்டுப்பாட்டு சிமுலேட்டர்",
    proactive_multi_sensor_hud: "செயலூக்க பன்முக சென்சார் HUD",
    start: "தொடங்கு",
    stop: "நிறுத்து",
    progress: "முன்னேற்றம்",
    step: "படி",
    ai_detections: "AI கண்டறிதல்கள்",
    patrol_dispatched: "🔴 ரோந்து வாகனம் அனுப்பப்பட்டது",
    elevated_alert: "🟡 உயர் எச்சரிக்கை நிலை",
    secure_level: "🟢 பாதுகாப்பான நிலை",
    simulator_idle: "சிமுலேட்டர் தயார் நிலையில் உள்ளது. 14-படி பாதுகாப்பு நிகழ்வைத் தொடங்க \"தொடங்கு\" பொத்தானை அழுத்தவும்.",
    alerts_feed: "அபாய எச்சரிக்கைகள்",
    patrol_dispatches: "ரோந்து வாகனங்கள்",
    no_active_alerts: "இதுவரை எந்தவொரு அபாய எச்சரிக்கையும் பதிவாகவில்லை.",
    cctv_evaluated_loop: "கேமரா நேரடி காட்சிகள் பகுப்பாய்வு செய்யப்படுகின்றன. AI கணினி செயலில் உள்ளது.",
    no_patrol_dispatches: "ரோந்து வாகனங்கள் அனுப்பப்படவில்லை.",
    escalated_alerts_routing: "தீவிரப்படுத்தப்பட்ட எச்சரிக்கைகள் ரோந்து வாகன வழிகாட்டுதலுக்கு இங்கே தோன்றும்.",
    escalated: "தீவிரப்படுத்தப்பட்டது",
    dispatched: "அனுப்பப்பட்டது",
    resolved: "தீர்வு செய்யப்பட்டது",
    dispatch_patrol: "ரோந்து வாகனத்தை அனுப்பு",
    resolve_case: "வழக்கை முடித்துவை",
    case_archived: "வழக்கு காப்பகப்படுத்தப்பட்டது",
    resolve: "தீர்க்கப்பட்டது",
    escalate: "தீவிரப்படுத்து",
    evidence: "சான்றுகள்",
    selected_feed: "தேர்ந்தெடுக்கப்பட்ட கேமரா",
    focus_analyzer: "நேரடி பகுப்பாய்வி / நேரடி பொருள் எல்லை பூட்டுகள்",
    fps: "FPS",
    latency: "தாமதம்",
    streaming_active: "நேரடி ஒளிபரப்பு செயலில் உள்ளது",
    take_snapshot: "புகைப்படம் எடு",
    start_recording: "பதிவை தொடங்கு",
    stop_recording: "பதிவை நிறுத்து",
    generate_report: "அறிக்கை தயாரி",
    emergency_alert: "அவசர எச்சரிக்கை",
    live_event_telemetry_logs: "நேரடி நிகழ்வு அளவீட்டு பதிவுகள்",
    ai_object_detection_status: "AI பொருள் கண்டறிதல் நிலை",
    person_detection: "மனிதர்கள் கண்டறிதல்",
    vehicle_detection: "வாகனங்கள் கண்டறிதல்",
    face_id_lock: "முக அடையாள பூட்டு",
    weapon_detection: "ஆயுதங்கள் கண்டறிதல்",
    fight_recognition: "சண்டை / போராட்டம் கண்டறிதல்",
    smoke_fire_engine: "புகை மற்றும் நெருப்பு கண்டறிதல்",
    abandoned_object_finder: "கைவிடப்பட்ட பொருள் கண்டறிதல்",
    detected: "🟢 கண்டறியப்பட்டது",
    locked: "🟢 பூட்டப்பட்டது",
    weapon_alert: "🔴 ஆயுதம் கண்டறியப்பட்டது",
    violence_alert: "🔴 வன்முறை கண்டறியப்பட்டது",
    fire_alert: "🔴 நெருப்பு எச்சரிக்கை",
    abandoned_alert: "🟡 கண்டறியப்பட்டது",
    safe_clear: "🟢 பாதுகாப்பானது",
    clear: "🟢 தெளிவானது",
    off: "முடக்கப்பட்டுள்ளது",
    decision_engine: "முடிவெடுக்கும் கணினி",
    ai_target_lock: "AI இலக்கு பூட்டு நம்பிக்கை",
    confidence: "நம்பிக்கை",
    executive_monitoring_dashboard: "நிர்வாக கண்காணிப்பு டாஷ்போர்டு",
    government_analytics: "அரசு பகுப்பாய்வு & அபாய அறிக்கை பிரிவுகள்",
    recent_alerts_log: "சமீபத்திய எச்சரிக்கை பதிவு",
    live_incident_timeline: "நேரடி சம்பவ காலவரிசை",
    cam: "கேமரா",
    location: "இடம்",
    risk: "அபாயம்",
    timestamp: "நேரம்",
    status: "நிலை",
    active_tamil_text: "வருமுன் காப்போம்",
    sec: "வி",
    min: "நிமி",
    subway_gate: "எச்சரிக்கை: இருட்டான சுரங்கப்பாதை கேட் அருகில் நபர் அதிக நெருக்க விகிதத்தைக் காட்டுகிறார்.",
    pedestrian_anomaly: "நடைபாதை முரண்பாடு எச்சரிக்கை.",
    critical_proximity: "அபாய எச்சரிக்கை: 70 விநாடிகளாக நெருக்கம் 1.0 மீட்டருக்கும் குறைவாக உள்ளது. இலக்கு பதற்றமான நடத்தையை காட்டினார்.",
    normal_flow: "இயல்பான நடைபாதை ஒழுங்கு. அனைத்து அளவீடுகளிலும் குறைந்த ஆபத்து நிலைகளே உள்ளன.",
    select_camera: "கண்காணிப்பு கேமராவைத் தேர்ந்தெடு",
    focused_feed: "வட்டார கண்காணிப்பு நேரடி திரை",
    threat_console: "அபாய எச்சரிக்கை நிகழ்வுப் பதிவுகள்",
    active_caps: "செயலில் உள்ளது"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
